In [1]:
# ==========================================
# Lesson 18 - Supervised vs Unsupervised Learning
# ==========================================

import ee
import geemap
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.ensemble import RandomForestRegressor
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split

ee.Initialize(project="oc-flux")

Map = geemap.Map()

# Study Area (Yamuna River)
point = ee.Geometry.Point([77.2090, 28.6139])

collection = (
    ee.ImageCollection("LANDSAT/LC08/C02/T1_L2")
    .filterBounds(point)
    .filterDate("2023-01-01", "2023-12-31")
)

image = collection.median()

Map.centerObject(point, 10)

Map

Map(center=[28.613900000000005, 77.209], controls=(WidgetControl(options=['position', 'transparent_bg'], posit…

In [ ]:
Python Example (Train/Test Split)

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

X = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

y = np.array([2,4,6,8,10,12,14,16,18,20])

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Samples")

print(X_train)

print()

print("Testing Samples")

print(X_test)

Training Samples
[[ 6]
 [ 1]
 [ 8]
 [ 3]
 [10]
 [ 5]
 [ 4]
 [ 7]]

Testing Samples
[[9]
 [2]]


In [ ]:
Observe that approximately 80% of the samples are used for training and 20% for testing.

In [ ]:
Supervised Learning Example

In [3]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(
    n_estimators=100,
    random_state=42
)

model.fit(X_train, y_train)

prediction = model.predict([[11]])

print("Prediction =", prediction)

Prediction = [18.48]


In [ ]:
The model predicts the output for a value it has never seen before.

In [ ]:
Unsupervised Learning Example

In [4]:
from sklearn.cluster import KMeans
import numpy as np

X = np.array([
    [1,2],
    [2,1],
    [8,9],
    [9,8]
])

kmeans = KMeans(
    n_clusters=2,
    random_state=42
)

kmeans.fit(X)

print(kmeans.labels_)

[0 0 1 1]


In [ ]:
This means:

First two points belong to one cluster.
Last two belong to another.

Notice that we never told the algorithm the correct answers.